---

- name: Ensure .kube directory exists on local
  local_action:
    module: file
    path: ~/.kube
    state: directory
    mode: '0755'
  run_once: true

- name: Fetch kubeconfig file to temporary location
  fetch:
    src: ~/.kube/config
    dest: ~/kubeconfig_{{ inventory_hostname }}
    flat: yes
  run_once: true

- name: Compare and update local kubeconfig if changed
  local_action:
    module: command
    args:
      cmd: diff ~/kubeconfig_{{ inventory_hostname }} ~/.kube/config || mv ~/kubeconfig_{{ inventory_hostname }} ~/.kube/config
  run_once: true