# TODO Investigate how to install Rancher via Ansible
#  https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha

---

- name: Deploy Cert Manager on k3s using Ansible
  hosts: localhost
  vars:
    cert_manager_version: "v1.15.1"  # Specify the cert-manager version here
    cert_manager_timeout: "300s"  # Increase timeout to 10 minutes
  tags:
    certs  
  tasks:
    - name: Add jetstack repository for cert-manager
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    # - name: Update helm repositories
    #   shell: helm repo update

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        namespace: cert-manager
        chart_ref: jetstack/cert-manager
        create_namespace: true
        update_repo_cache: true
        set_values: 
          - value: "crds.enabled=true"
            value_type: string
        


    - name: Wait for cert-manager pods to be ready
      shell: kubectl wait --namespace cert-manager --for=condition=Ready pod --all --timeout={{ cert_manager_timeout }}



- name: Deploy Rancher on k3s using Ansible
  hosts: localhost
  vars:
    # ansible_connection: kubernetes.core.kubectl
    # ansible_kubectl_namespace: cattle-system
    # ansible_kubectl_extra_args: 
    rancher_hostname: "rancher.home.penguinrookery.co.uk"
  tags:
    rancher
  tasks:
    - name: Add Helm repository for Rancher charts
      kubernetes.core.helm_repository:
        name: rancher-latest
        repo_url: https://releases.rancher.com/server-charts/latest
    - name: Install Rancher
      kubernetes.core.helm:
        name: rancher
        namespace: cattle-system
        chart_ref: rancher-latest/rancher
        create_namespace: true
        update_repo_cache: true
        set_values: 
          - value: "hostname={{ rancher_hostname }}"
            value_type: string
          - value: "bootstrapPassword=pH3ORw8HRblLI3Dn"
            value_type: string
          # - value: "bootstrapPassword=admin"
          #   value_type: string

    - name: Expose Rancher deployment as a LoadBalancer service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: rancher-lb
            namespace: cattle-system
          spec:
            selector:
              app: rancher
            ports:
              - protocol: TCP
                port: 443
                targetPort: 443
            type: LoadBalancer

    # - name: Expose rancher externally
    #   kubernetes.core.kubectl:
    #     command: "expose deployment rancher --name=rancher-lb --port=443 --type=LoadBalancer"

    # # kubectl expose deployment rancher --name=rancher-lb --port=443 --type=LoadBalancer -n cattle-system